services:
  - name: wordpress
    type: web
    env: docker
    repo: https://github.com/Datpt-pce/hannahenglish-wordpress.git
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        value: your-mysql-host
      - key: WORDPRESS_DB_USER
        value: your-mysql-user
      - key: WORDPRESS_DB_PASSWORD
        value: your-mysql-password
      - key: WORDPRESS_DB_NAME
        value: wordpress_db
